import type { Room, Teacher, Instrument, Lesson, Student } from "./types"

export const mockRooms: Room[] = [
  {
    id: "room-1",
    name: "Sala Fortepianowa A",
    capacity: 2,
    instruments: ["Pianino", "Keyboard"],
    available: true,
    hourlyRate: 30,
    description: "Mała sala z pianinem akustycznym, idealna na lekcje indywidualne",
  },
  {
    id: "room-2",
    name: "Sala Gitarowa B",
    capacity: 4,
    instruments: ["Gitara", "Gitara basowa", "Wzmacniacz"],
    available: true,
    hourlyRate: 35,
    description: "Sala wyposażona w gitary i wzmacniacze",
  },
  {
    id: "room-3",
    name: "Sala Perkusyjna C",
    capacity: 6,
    instruments: ["Perkusja", "Pady elektroniczne"],
    available: false,
    hourlyRate: 40,
    description: "Sala z pełnym zestawem perkusyjnym i padami",
  },
  {
    id: "room-4",
    name: "Sala Zespołowa D",
    capacity: 8,
    instruments: ["Gitara", "Gitara basowa", "Perkusja", "Pianino", "Mikrofony"],
    available: true,
    hourlyRate: 50,
    description: "Duża sala do prób zespołowych z pełnym wyposażeniem",
  },
  {
    id: "room-5",
    name: "Studio Koncertowe",
    capacity: 10,
    instruments: ["Pianino", "Perkusja", "Gitara", "System nagłośnieniowy", "Mikrofony"],
    available: true,
    hourlyRate: 80,
    description: "Profesjonalne studio z systemem nagłośnieniowym i oświetleniem scenicznym",
  },
]

export const mockTeachers: Teacher[] = [
  {
    id: "teacher-1",
    name: "Anna Kowalska",
    instruments: ["Pianino", "Keyboard"],
    available: true,
    email: "anna.kowalska@szkola.pl",
    phone: "+48 123 456 789",
    experience: 8,
    hourlyRate: 80,
    bio: "Absolwentka Akademii Muzycznej, specjalizuje się w muzyce klasycznej i jazzowej",
  },
  {
    id: "teacher-2",
    name: "Piotr Nowak",
    instruments: ["Gitara", "Gitara basowa"],
    available: true,
    email: "piotr.nowak@szkola.pl",
    phone: "+48 234 567 890",
    experience: 12,
    hourlyRate: 90,
    bio: "Gitarzysta z wieloletnim doświadczeniem w zespołach rockowych i bluesowych",
  },
  {
    id: "teacher-3",
    name: "Marcin Wiśniewski",
    instruments: ["Perkusja"],
    available: true,
    email: "marcin.wisniewski@szkola.pl",
    phone: "+48 345 678 901",
    experience: 10,
    hourlyRate: 85,
    bio: "Perkusista sesyjny, specjalista od rytmów latynoskich i jazzowych",
  },
  {
    id: "teacher-4",
    name: "Katarzyna Dąbrowska",
    instruments: ["Pianino", "Wokal"],
    available: false,
    email: "katarzyna.dabrowska@szkola.pl",
    phone: "+48 456 789 012",
    experience: 15,
    hourlyRate: 100,
    bio: "Wokalistka i pianistka, prowadzi zajęcia z techniki wokalnej i interpretacji",
  },
  {
    id: "teacher-5",
    name: "Tomasz Zieliński",
    instruments: ["Gitara", "Ukulele"],
    available: true,
    email: "tomasz.zielinski@szkola.pl",
    phone: "+48 567 890 123",
    experience: 6,
    hourlyRate: 70,
    bio: "Młody nauczyciel specjalizujący się w muzyce popularnej i fingerstyle",
  },
  {
    id: "teacher-6",
    name: "Magdalena Lewandowska",
    instruments: ["Pianino", "Gitara", "Wokal"],
    available: true,
    email: "magdalena.lewandowska@szkola.pl",
    phone: "+48 678 901 234",
    experience: 20,
    hourlyRate: 120,
    bio: "Doświadczona nauczycielka, prowadzi zajęcia grupowe i indywidualne z wielu instrumentów",
  },
]

export const getInstrumentsFromTeachers = (teachers: Teacher[]): Instrument[] => {
  const instrumentsSet = new Set<string>()

  teachers.forEach((teacher) => {
    teacher.instruments.forEach((instrument) => {
      instrumentsSet.add(instrument)
    })
  })

  return Array.from(instrumentsSet).map((instrument, index) => ({
    id: `inst-${index + 1}`,
    name: instrument,
    type: getInstrumentType(instrument),
    available: true,
  }))
}

const getInstrumentType = (instrument: string): string => {
  const types: { [key: string]: string } = {
    Pianino: "Instrumenty klawiszowe",
    Keyboard: "Instrumenty klawiszowe",
    Gitara: "Instrumenty strunowe",
    "Gitara basowa": "Instrumenty strunowe",
    Ukulele: "Instrumenty strunowe",
    Perkusja: "Instrumenty perkusyjne",
    Wokal: "Wokal",
  }
  return types[instrument] || "Inne"
}

export const mockLessons: Lesson[] = [
  {
    id: "lesson-1",
    title: "Lekcja pianina - Anna Kowalska",
    type: "individual-stationary",
    date: "2024-01-15",
    startTime: "10:00",
    endTime: "10:45",
    duration: 45,
    teacher: "Anna Kowalska",
    room: "Sala Fortepianowa A",
    instrument: "Pianino",
    students: ["Jan Kowalski"],
    maxParticipants: 1,
    priceType: "total",
    price: 80,
    studentPayments: { "Jan Kowalski": true },
  },
  {
    id: "lesson-2",
    title: "Warsztat zespołowy COMBO",
    type: "group",
    date: "2024-01-15",
    startTime: "18:00",
    endTime: "19:30",
    duration: 90,
    teacher: "Piotr Nowak",
    room: "Sala Zespołowa D",
    instrument: "Gitara",
    students: ["Maria Nowak", "Piotr Kowalczyk", "Anna Wiśniewska"],
    maxParticipants: 6,
    priceType: "per-person",
    price: 50,
    studentPayments: {
      "Maria Nowak": true,
      "Piotr Kowalczyk": false,
      "Anna Wiśniewska": true,
    },
    description: "Warsztat gry w zespole - rock i blues",
  },
  {
    id: "lesson-3",
    title: "Lekcja perkusji online",
    type: "individual-online",
    date: "2024-01-15",
    startTime: "16:00",
    endTime: "16:45",
    duration: 45,
    teacher: "Marcin Wiśniewski",
    instrument: "Perkusja",
    students: ["Tomasz Dąbrowski"],
    maxParticipants: 1,
    priceType: "total",
    price: 70,
    studentPayments: { "Tomasz Dąbrowski": false },
  },
  {
    id: "lesson-4",
    title: "Zajęcia umuzykalniające dla dzieci",
    type: "children",
    date: "2024-01-16",
    startTime: "15:00",
    endTime: "15:45",
    duration: 45,
    teacher: "Magdalena Lewandowska",
    room: "Sala Gitarowa B",
    instrument: "Pianino",
    students: ["Zosia Kowalska", "Kacper Nowak"],
    maxParticipants: 8,
    priceType: "per-person",
    price: 40,
    studentPayments: {
      "Zosia Kowalska": true,
      "Kacper Nowak": true,
    },
    description: "Nauka podstaw muzyki przez zabawę",
  },
  {
    id: "lesson-5",
    title: "Wynajem sali prób",
    type: "practice-room",
    date: "2024-01-16",
    startTime: "20:00",
    endTime: "21:00",
    duration: 60,
    teacher: "",
    room: "Sala Perkusyjna C",
    instrument: "Perkusja",
    students: ["Zespół Rockowy XYZ"],
    maxParticipants: 4,
    priceType: "total",
    price: 40,
    studentPayments: { "Zespół Rockowy XYZ": true },
    description: "Próba zespołu rockowego",
  },
]

export const mockStudents: Student[] = [
  {
    id: "student-1",
    firstName: "Jan",
    lastName: "Kowalski",
    email: "jan.kowalski@email.com",
    phone: "+48 123 456 789",
    dateOfBirth: "2005-03-15",
    hasActiveSubscription: true,
  },
  {
    id: "student-2",
    firstName: "Maria",
    lastName: "Nowak",
    email: "maria.nowak@email.com",
    phone: "+48 234 567 890",
    dateOfBirth: "1998-07-22",
    hasActiveSubscription: true,
  },
  {
    id: "student-3",
    firstName: "Piotr",
    lastName: "Kowalczyk",
    email: "piotr.kowalczyk@email.com",
    phone: "+48 345 678 901",
    dateOfBirth: "2000-11-08",
    hasActiveSubscription: false,
  },
  {
    id: "student-4",
    firstName: "Anna",
    lastName: "Wiśniewska",
    email: "anna.wisniewska@email.com",
    phone: "+48 456 789 012",
    dateOfBirth: "2002-01-30",
    hasActiveSubscription: true,
  },
  {
    id: "student-5",
    firstName: "Tomasz",
    lastName: "Dąbrowski",
    email: "tomasz.dabrowski@email.com",
    phone: "+48 567 890 123",
    dateOfBirth: "1995-09-12",
    hasActiveSubscription: false,
  },
  {
    id: "student-6",
    firstName: "Zosia",
    lastName: "Kowalska",
    email: "zosia.kowalska@email.com",
    phone: "+48 678 901 234",
    dateOfBirth: "2015-05-18",
    hasActiveSubscription: true,
  },
  {
    id: "student-7",
    firstName: "Kacper",
    lastName: "Nowak",
    email: "kacper.nowak@email.com",
    phone: "+48 789 012 345",
    dateOfBirth: "2014-12-03",
    hasActiveSubscription: true,
  },
  {
    id: "student-8",
    firstName: "Magdalena",
    lastName: "Zielińska",
    email: "magdalena.zielinska@email.com",
    phone: "+48 890 123 456",
    dateOfBirth: "1992-04-25",
    hasActiveSubscription: false,
  },
]
